### PR TITLE
Updated timestamps to UTC

### LINKED ISSUE #118: Update snippet timestamp to UTC time
## Expected Behavior

`UpdateIndexFile` and `SaveSnippetToS3` should save/add the timestamp in UTC format. The batch update lambda will also need to run through all existing `index.json`s and update their timestamps into UTC format.

## Current Behavior

The lambdas save/update the timestamp [using the local timezone](https://github.com/maryvilledev/codesplain-lambdas/blob/master/lambdas/SaveSnippetToS3/lambda_function.py#L111).

## Possible Solution

Use [`utcnow()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow).

### PR DESCRIPTION
**Pull request by dane-johnson**
## Description

All timestamps are now UTC
## Motivation and Context

Closes #118
## Checklist:

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by thebho** [comment]
Will we need to re-run the generate index lambda?
And is that lambda up to date and tested?  You could create a different named index file in dev to test

**Comment by Hopding** [comment]
If we re-run `GenerateIndexFiles`, will that not change the `lastEdited` field of all the snippets to the current time in UTC, as opposed to converting their existing timestamps to UTC?

**Comment by thebho** [comment]
I thought it pulls the metadata from S3 and uses that

**Comment by dane-johnson** [comment]
@thebho is right

**Comment by dane-johnson** [comment]
And yes there is an up to date test.

**Comment by thebho** [comment]
Cool, so we would need to run the lambda in dev when it is merged and prod when we release?

**Pull request merged**
