### PR TITLE
Check for pre-existing keys

### LINKED ISSUE #3: The savesnippet lambda needs to check if a key has already been used
We shouldn't be able to overwrite a snippet when posting.  Add logic to append a `-1` to the key

### PR DESCRIPTION
**Pull request by solkaz**
## Description
Refactors SaveSnippetToS3 to check if a key exists, and if it does, it updates the snippet's title to use that key

## Motivation and Context
fixes #3 

## Checklist:

- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by thebho** [comment]
The description a little confusing.  Just to confirm:
A snippet arrives with a key
If that title -> key is unique save to S3
If not, add a _1 to the key and try again

What happens if key_1 is also in use?

**Comment by solkaz** [comment]
1. Snippet + associated data sent to a lambda.
2. Check that the title is being used as a key already. If not, then it will first append `_1` to it
3. If that new key (title + `_1`) is already being used, then it will attempt `_2`, then `_3`, and so on

**Comment by thebho** [comment]
Cool, thanks for clearing that up

**Comment by thebho** [comment]
We should add some Postman tests to verify that behavior

**Pull request merged**
